config/routes.rb
Rails.application.routes.draw do
 resources :songs
 resources :users, only: [:new, :create, :show]
 root to: "songs#index"
 get '/login', to: "sessions#new"
 post '/login', to: "sessions#create"
 delete '/logout', to: "sessions#destroy", as: "logout"
 get '/no_track', to: "songs#no_track"
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true, uniqueness: { scope: :artist, message: "song already exists for artist" }
  validates :artist, presence: true

  def sound_cloud
    if self.song_url
      url ||= [self.song_url,'&amp;auto_play=false&amp;hide_related=false&amp;show_comments=false&amp;show_user=true&amp;show_reposts=false&amp;visual=true'].join
    else
      url ||= '/no_track'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = "Cannot login"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.order(:artist)
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      session[:most_recent_song_title] = @song.title
      flash[:notice] = "Song successfully created!"
      redirect_to song_path(@song)
    elsif @song.title.blank?
      flash[:error] = "Song is missing title"
      render :new
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    session[:most_recent_song_title] = Song.all.last.title
    redirect_to songs_path
  end

  def no_track
    render :no_track
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist, :song_url)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User successfully created!"
      redirect_to root_path
    else
      flash[:error] = "User not created!"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <% if current_user %>
        <span class="mdl-layout-title"><%= current_user.username %></span>
        <!-- Add spacer, to align navigation to the right -->
        <div class="mdl-layout-spacer"></div>
         <!-- Navigation. We hide it in small screens. -->
        <nav class="mdl-navigation mdl-layout--large-screen-only">
            <%= link_to "Logout", logout_path, method: :delete %>
        </nav>
      <% else %>
          <span class="mdl-layout-title"><%= link_to "Create User", new_user_path %></span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <%= link_to "Login", login_path %>
          </nav>
     <% end %>
    </div>
  </header>
<div id="newest_song">
  <strong>Newest song:</strong> <%= session[:most_recent_song_title] %>
</div>
<% flash.each do |type, msg| %>
    <%= content_tag  :div, msg, class: "flash_#{type}"%>
<% end %>
<%= yield %>
</body>
</html>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>
<%= render partial: 'songs/shared/form'%>

app/views/songs/index.html.erb
<h1 id="my_jams">My Jams</h1>
  <%= link_to '<button id="create_song" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Create New Song</button>'.html_safe, new_song_path %></button>

<div class="demo-grid-1 mdl-grid">
    <% @songs.each do |song| %>
      <div class="mdl-cell mdl-cell--4-col">
        <div class="mdl-card mdl-shadow--2dp demo-card-wide">
          <div class="mdl-card__title">
            <h3 class="mdl-card__title-text"><%= song.artist %></h3>
          </div>
          <div class="mdl-card__media">
            <i id="song_link"><%= link_to song.title, song_path(song) %></i>
          </div>
          <div class="mdl-card__actions mdl-card--border">
              <iframe width="100%" height="200" scrolling="no" frameborder="no" src='<%= song.sound_cloud %>'></iframe>
          </div>
          <div class="mdl-card__menu">
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
              <i class="material-icons">share</i>
            </button>
          </div>
        </div>
      </div>
<% end %>
</div>

app/views/songs/new.html.erb
<h1 id="create_song_title">Create a Song</h1>
<%= render partial: 'songs/shared/form'%>

app/views/songs/no_track.html.erb
<h1 id="no_song">NO SONG</h1>

app/views/songs/shared/_form.html.erb
<%= form_for(@song) do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :artist %>
        <%= f.text_field :artist %>
        <%= f.label :song_url %>
        <%= f.text_field :song_url %>
        <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1 id="show_song_title"><%= @song.title %></h1>
<h3><%= @song.artist %></h3>

<h6><%= link_to "Edit song", edit_song_path(@song) %></h6>
<h6><%= link_to "Delete song", song_path(@song), method: :delete %></h6>
<h6><%= link_to "Back to Song List", songs_path %></h6>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %> <br>

    <%= f.label :password %>
    <%= f.password_field :password %> <br>

    <%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>